### ISSUE TITLE
Deberían haberlo puesto en desarrollo

### ISSUE THREAD

**Issue by paoloose** [mAI-solutions/mAI#44]
Wong dijo que las líneas base son puntos en el tiempo de la carpeta de desarrollo, que es donde todos su documentos deberían estar

👎👎👎👎👎

**Comment by luedu1103** [comment]
Cierto, todo el "desarrollo" del proyecto debe estar en la carpeta desarrollo. Las líneas base solo sirven como checkpoints para cada hito.

👎👎👎👎👎👎👎👎
